[package]
name = "duty_roster"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rand = "0.9.2"
serde = {version="1.0.219", features = ["derive"]}
serde_with = {version="3.14.0", features = ["chrono"]}
toml = "0.9.5"
