[advisories]
ignore = [
    "RUSTSEC-2024-0436", # paste is unmaintained
    "RUSTSEC-2024-0384", # instant is unmaintained
    "RUSTSEC-2026-0002", # lru has a soundness issue
]

[output]
format = "terminal"
quiet = false
show-tree = true
